"""empty message

Revision ID: 0fb7fb265036
Revises: 
Create Date: 2024-03-17 18:05:38.887685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fb7fb265036'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Property_Info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('propertytitle', sa.String(length=255), nullable=True),
    sa.Column('propertydescription', sa.String(length=1024), nullable=True),
    sa.Column('propertytype', sa.String(length=80), nullable=True),
    sa.Column('photo', sa.String(length=255), nullable=True),
    sa.Column('numberofbedrooms', sa.Integer(), nullable=True),
    sa.Column('numberofbathrooms', sa.Integer(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('propertylocation', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Property_Info')
    # ### end Alembic commands ###
